### PR TITLE
add: docker compose

### PR DESCRIPTION
**Pull request by mateuspinto**
Add a simple mini project in Spring Boot already configured with Docker Compose and MySQL. 

It will be used to build our software on top.

### CODE REVIEW

**Comment by joaoPraiaJunior** [comment]
@mateuspinto I changed the docker-compose.yml document. Previously, the application started in a loop until the database was up and running. Now the application waits a few seconds for the database image to become stable and then the application starts building. Please check that everything is ok and I will approve it.

**Comment by mateuspinto** [comment]
I tested the changes and it works. Very interesting and useful additions.

**Review by joaoPraiaJunior — APPROVED** [review]
Aprovado!

**Comment by joaoPraiaJunior** [comment]
@mateuspinto @Jarandia69  Merge done

**Pull request merged**
